### ISSUE TITLE
Grad Jobs Still Available

### ISSUE THREAD

**Issue by Fraser-G** [ensoft/about#1]
Hello,

I'd like to know if your grad roles are still open for applications. I have a leaflet from a careers fair that says applications are open until 15th November, but I can only find internships on Cisco's careers page.

Thanks,
Fraser

**Comment by simonchatts** [comment]
Hi Fraser,

We've been rather overwhelmed by quality applications this year, and have had to close the application window a little early. So I'm afraid the leaflet is out of date.

If we open up for additional grad roles between now and September 2024, you'll be able to see by [searching here](https://jobs.cisco.com/jobs/SearchJobs/ensoft?listFilterMode=1).

Best of luck with your ongoing search!

Simon
